-- =========================================================================
-- CƠ SỞ DỮ LIỆU TOÀN DIỆN 15 BẢNG (15 TABLES ENTERPRISE SCHEMA - 3NF)
-- HỆ THỐNG TRUYỀN THÔNG & QUẢN TRỊ CÔNG ĐOÀN ĐẠI HỌC THỦ DẦU MỘT (TDMU)
-- MICROSOFT SQL SERVER 2019/2022 | Server: RTX-ON\MSSQLVESE
-- Database: TDMU_TradeUnion_DB
-- =========================================================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TDMU_TradeUnion_DB')
BEGIN
    CREATE DATABASE TDMU_TradeUnion_DB;
END
GO

USE TDMU_TradeUnion_DB;
GO

-- Xóa các bảng cũ theo thứ tự ràng buộc khóa ngoại
IF OBJECT_ID('dbo.FEEDBACK', 'U') IS NOT NULL DROP TABLE dbo.FEEDBACK;
IF OBJECT_ID('dbo.PUBLISH_LOGS', 'U') IS NOT NULL DROP TABLE dbo.PUBLISH_LOGS;
IF OBJECT_ID('dbo.TEMPLATES', 'U') IS NOT NULL DROP TABLE dbo.TEMPLATES;
IF OBJECT_ID('dbo.WELFARE_APPLICATIONS', 'U') IS NOT NULL DROP TABLE dbo.WELFARE_APPLICATIONS;
IF OBJECT_ID('dbo.BENEFITS', 'U') IS NOT NULL DROP TABLE dbo.BENEFITS;
IF OBJECT_ID('dbo.BOOKMARKS', 'U') IS NOT NULL DROP TABLE dbo.BOOKMARKS;
IF OBJECT_ID('dbo.COMMENTS', 'U') IS NOT NULL DROP TABLE dbo.COMMENTS;
IF OBJECT_ID('dbo.ARTICLE_AUDITS', 'U') IS NOT NULL DROP TABLE dbo.ARTICLE_AUDITS;
IF OBJECT_ID('dbo.USERS', 'U') IS NOT NULL DROP TABLE dbo.USERS;
IF OBJECT_ID('dbo.SCHEDULES', 'U') IS NOT NULL DROP TABLE dbo.SCHEDULES;
IF OBJECT_ID('dbo.MONTHLY_REPORTS', 'U') IS NOT NULL DROP TABLE dbo.MONTHLY_REPORTS;
IF OBJECT_ID('dbo.DOCUMENTS', 'U') IS NOT NULL DROP TABLE dbo.DOCUMENTS;
IF OBJECT_ID('dbo.ARTICLES', 'U') IS NOT NULL DROP TABLE dbo.ARTICLES;
IF OBJECT_ID('dbo.CATEGORIES', 'U') IS NOT NULL DROP TABLE dbo.CATEGORIES;
IF OBJECT_ID('dbo.STAFF', 'U') IS NOT NULL DROP TABLE dbo.STAFF;
IF OBJECT_ID('dbo.UNION_GROUPS', 'U') IS NOT NULL DROP TABLE dbo.UNION_GROUPS;
IF OBJECT_ID('dbo.ORGANIZATIONS', 'U') IS NOT NULL DROP TABLE dbo.ORGANIZATIONS;
GO

-- =========================================================================
-- NHÓM 1: 8 BẢNG QUẢN TRỊ CỐT LÕI (CORE GOVERNANCE & CONTENT)
-- =========================================================================

-- 1. BẢNG TO_CHUC (5 Ban chuyên môn cấp Trường)
CREATE TABLE dbo.ORGANIZATIONS (
    OrganizationId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    Term NVARCHAR(50) NOT NULL DEFAULT N'Nhiệm kỳ 2023 - 2028',
    Description NVARCHAR(MAX) NULL,
    DisplayOrder INT DEFAULT 1,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME()
);

-- 2. BẢNG TO_CONG_DOAN (16 Tổ công đoàn bộ phận)
CREATE TABLE dbo.UNION_GROUPS (
    UnionGroupId INT IDENTITY(1,1) PRIMARY KEY,
    Code VARCHAR(50) UNIQUE NOT NULL,
    Name NVARCHAR(150) NOT NULL,
    LeaderName NVARCHAR(100) NULL,
    Email VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    OfficeAddress NVARCHAR(150) NULL,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME()
);

-- 3. BẢNG NHAN_SU (Cán bộ giảng viên đoàn viên)
CREATE TABLE dbo.STAFF (
    StaffId INT IDENTITY(1,1) PRIMARY KEY,
    UnionGroupId INT NOT NULL,
    OrganizationId INT NULL,
    StaffCode VARCHAR(50) UNIQUE NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    Gender NVARCHAR(10) DEFAULT N'Nam',
    DateOfBirth DATE NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Phone VARCHAR(20) NULL,
    AcademicTitle NVARCHAR(50) NULL,
    UnionRole NVARCHAR(100) DEFAULT N'Đoàn viên',
    ProfessionalRole NVARCHAR(100) NULL,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_STAFF_UNIONGROUP FOREIGN KEY (UnionGroupId) REFERENCES dbo.UNION_GROUPS(UnionGroupId),
    CONSTRAINT FK_STAFF_ORGANIZATION FOREIGN KEY (OrganizationId) REFERENCES dbo.ORGANIZATIONS(OrganizationId) ON DELETE SET NULL
);

-- 4. BẢNG CATEGORIES (Chuyên mục bài viết)
CREATE TABLE dbo.CATEGORIES (
    CategoryId INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Slug VARCHAR(120) UNIQUE NOT NULL,
    Description NVARCHAR(MAX) NULL,
    DisplayOrder INT DEFAULT 1,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME()
);

-- 5. BẢNG ARTICLES (Bài viết & Tòa soạn AI Đa Kênh)
CREATE TABLE dbo.ARTICLES (
    ArticleId INT IDENTITY(1,1) PRIMARY KEY,
    AuthorId INT NOT NULL,
    CategoryId INT NULL,
    Title NVARCHAR(255) NOT NULL,
    Slug VARCHAR(255) UNIQUE NOT NULL,
    Summary NVARCHAR(MAX) NULL,
    Content NVARCHAR(MAX) NOT NULL,
    FeaturedImage VARCHAR(500) NULL,
    FacebookContent NVARCHAR(MAX) NULL,
    ZaloContent NVARCHAR(MAX) NULL,
    VideoScript NVARCHAR(MAX) NULL,
    IsAiGenerated BIT DEFAULT 0,
    AiPrompt NVARCHAR(MAX) NULL,
    Status VARCHAR(20) DEFAULT 'draft',
    ViewCount INT DEFAULT 0,
    LikeCount INT DEFAULT 0,
    PublishedDate DATETIME2 NULL,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME(),
    UpdatedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_ARTICLES_AUTHOR FOREIGN KEY (AuthorId) REFERENCES dbo.STAFF(StaffId),
    CONSTRAINT FK_ARTICLES_CATEGORY FOREIGN KEY (CategoryId) REFERENCES dbo.CATEGORIES(CategoryId) ON DELETE SET NULL
);

-- 6. BẢNG DOCUMENTS (Kho văn bản chỉ đạo & biểu mẫu)
CREATE TABLE dbo.DOCUMENTS (
    DocumentId INT IDENTITY(1,1) PRIMARY KEY,
    UploadedById INT NOT NULL,
    ReferenceNumber VARCHAR(100) NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    DocumentType VARCHAR(50) NOT NULL DEFAULT 'tuyentruyen',
    IssuingAgency NVARCHAR(150) NOT NULL DEFAULT N'Ban Thường Vụ Công Đoàn TDMU',
    IssueDate DATE NOT NULL,
    SignerName NVARCHAR(100) NULL,
    Attachment VARCHAR(500) NOT NULL,
    FileSize VARCHAR(50) DEFAULT '1.5 MB',
    DownloadCount INT DEFAULT 0,
    Notes NVARCHAR(MAX) NULL,
    PublishedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_DOCUMENTS_UPLOADER FOREIGN KEY (UploadedById) REFERENCES dbo.STAFF(StaffId)
);

-- 7. BẢNG MONTHLY_REPORTS (Báo cáo tháng định kỳ 16 Tổ CĐ - BM-02/CĐ)
CREATE TABLE dbo.MONTHLY_REPORTS (
    ReportId INT IDENTITY(1,1) PRIMARY KEY,
    UnionGroupId INT NOT NULL,
    ReporterId INT NOT NULL,
    Month INT NOT NULL,
    Year INT NOT NULL DEFAULT 2026,
    TotalStaff INT DEFAULT 0,
    TotalMembers INT DEFAULT 0,
    TotalFemaleMembers INT DEFAULT 0,
    NewMembers INT DEFAULT 0,
    MembersJoiningParty INT DEFAULT 0,
    MembersSupported INT DEFAULT 0,
    TotalSupportAmount DECIMAL(15, 2) DEFAULT 0,
    PropagandaContent NVARCHAR(MAX) NULL,
    OtherActivities NVARCHAR(MAX) NULL,
    NextMonthPlan NVARCHAR(MAX) NULL,
    Recommendations NVARCHAR(MAX) NULL,
    EvidenceLink VARCHAR(500) NULL,
    SelfAssessment NVARCHAR(100) DEFAULT N'Hoàn thành tốt nhiệm vụ (Loại B)',
    BoardRating NVARCHAR(100) DEFAULT N'Chờ duyệt',
    Status VARCHAR(20) DEFAULT 'Submitted',
    SubmittedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_MONTHLYREPORTS_UNIONGROUP FOREIGN KEY (UnionGroupId) REFERENCES dbo.UNION_GROUPS(UnionGroupId) ON DELETE CASCADE,
    CONSTRAINT FK_MONTHLYREPORTS_REPORTER FOREIGN KEY (ReporterId) REFERENCES dbo.STAFF(StaffId)
);

-- 8. BẢNG SCHEDULES (Lịch hẹn giờ xuất bản đa kênh)
CREATE TABLE dbo.SCHEDULES (
    ScheduleId INT IDENTITY(1,1) PRIMARY KEY,
    ArticleId INT NOT NULL,
    Channel VARCHAR(50) NOT NULL DEFAULT 'Website',
    PublishAt DATETIME2 NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    ErrorNote NVARCHAR(MAX) NULL,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_SCHEDULES_ARTICLE FOREIGN KEY (ArticleId) REFERENCES dbo.ARTICLES(ArticleId) ON DELETE CASCADE
);

-- =========================================================================
-- NHÓM 2: 7 BẢNG BỔ TRỢ TƯƠNG TÁC, PHÚC LỢI & KIỂM TOÁN (INTERACTIVE PORTAL & WELFARE)
-- =========================================================================

-- 9. BẢNG USERS (Tài khoản xác thực & phân quyền 3 Role)
CREATE TABLE dbo.USERS (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    StaffId INT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    Role VARCHAR(20) NOT NULL DEFAULT 'Contributor',
    AvatarUrl VARCHAR(500) NULL,
    LastLoginAt DATETIME2 NULL,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_USERS_STAFF FOREIGN KEY (StaffId) REFERENCES dbo.STAFF(StaffId) ON DELETE SET NULL
);

-- 10. BẢNG ARTICLE_AUDITS (Lịch sử tác nghiệp & vết duyệt bài)
CREATE TABLE dbo.ARTICLE_AUDITS (
    AuditId INT IDENTITY(1,1) PRIMARY KEY,
    ArticleId INT NOT NULL,
    UserId INT NOT NULL,
    Action VARCHAR(100) NOT NULL,
    Note NVARCHAR(MAX) NULL,
    IpAddress VARCHAR(45) NULL,
    PerformedAt DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_ARTICLEAUDITS_ARTICLE FOREIGN KEY (ArticleId) REFERENCES dbo.ARTICLES(ArticleId) ON DELETE CASCADE,
    CONSTRAINT FK_ARTICLEAUDITS_USER FOREIGN KEY (UserId) REFERENCES dbo.USERS(UserId)
);

-- 11. BẢNG COMMENTS (Bình luận bài viết của đoàn viên)
CREATE TABLE dbo.COMMENTS (
    CommentId INT IDENTITY(1,1) PRIMARY KEY,
    ArticleId INT NOT NULL,
    UserId INT NULL,
    AuthorName NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL,
    Title NVARCHAR(100) NULL,
    Content NVARCHAR(MAX) NOT NULL,
    Status VARCHAR(20) DEFAULT 'approved',
    CreatedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_COMMENTS_ARTICLE FOREIGN KEY (ArticleId) REFERENCES dbo.ARTICLES(ArticleId) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_USER FOREIGN KEY (UserId) REFERENCES dbo.USERS(UserId) ON DELETE SET NULL
);

-- 12. BẢNG BOOKMARKS (Tủ sách đọc sau cá nhân)
CREATE TABLE dbo.BOOKMARKS (
    BookmarkId INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NULL,
    StaffCode VARCHAR(50) NULL,
    ArticleId INT NOT NULL,
    Title NVARCHAR(255) NULL,
    Note NVARCHAR(255) NULL,
    SavedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_BOOKMARKS_ARTICLE FOREIGN KEY (ArticleId) REFERENCES dbo.ARTICLES(ArticleId) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKMARKS_USER FOREIGN KEY (UserId) REFERENCES dbo.USERS(UserId) ON DELETE SET NULL
);

-- 13. BẢNG PHUC_LOI (Các gói chương trình phúc lợi đoàn viên)
CREATE TABLE dbo.BENEFITS (
    BenefitId INT IDENTITY(1,1) PRIMARY KEY,
    Code VARCHAR(50) UNIQUE NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Category VARCHAR(50) DEFAULT 'le_tet',
    EligibleSubjects NVARCHAR(200) NOT NULL,
    SupportAmount NVARCHAR(150) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Icon VARCHAR(50) DEFAULT 'fa-gift',
    Status VARCHAR(20) DEFAULT 'active',
    CreatedDate DATETIME2 DEFAULT SYSDATETIME()
);

-- 14. BẢNG DON_TRO_CAP (Đơn xin trợ cấp & chăm lo khó khăn)
CREATE TABLE dbo.WELFARE_APPLICATIONS (
    ApplicationId INT IDENTITY(1,1) PRIMARY KEY,
    StaffId INT NULL,
    BenefitId INT NULL,
    ApplicantName NVARCHAR(100) NOT NULL,
    Department NVARCHAR(150) NOT NULL,
    SupportType NVARCHAR(150) NOT NULL,
    RequestedAmount DECIMAL(15, 2) DEFAULT 0,
    ApprovedAmount DECIMAL(15, 2) NULL,
    Reason NVARCHAR(MAX) NOT NULL,
    SupportingDocument VARCHAR(500) NULL,
    Status VARCHAR(20) DEFAULT 'pending',
    ReviewerName NVARCHAR(100) NULL,
    Note NVARCHAR(MAX) NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    SubmittedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_WELFAREAPPLICATIONS_STAFF FOREIGN KEY (StaffId) REFERENCES dbo.STAFF(StaffId) ON DELETE SET NULL,
    CONSTRAINT FK_WELFAREAPPLICATIONS_BENEFIT FOREIGN KEY (BenefitId) REFERENCES dbo.BENEFITS(BenefitId) ON DELETE SET NULL
);

-- 15. BẢNG INBOX_FEEDBACK (Hòm thư góp ý & phản ánh gửi BCH)
CREATE TABLE dbo.FEEDBACK (
    FeedbackId INT IDENTITY(1,1) PRIMARY KEY,
    StaffId INT NULL,
    HandlerId INT NULL,
    FullName NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NULL,
    Department NVARCHAR(150) NULL,
    Topic NVARCHAR(150) NOT NULL,
    Subject NVARCHAR(255) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    Attachment VARCHAR(500) NULL,
    Status VARCHAR(20) DEFAULT 'pending',
    Reply NVARCHAR(MAX) NULL,
    SubmittedDate DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_FEEDBACK_STAFF FOREIGN KEY (StaffId) REFERENCES dbo.STAFF(StaffId) ON DELETE SET NULL,
    CONSTRAINT FK_FEEDBACK_HANDLER FOREIGN KEY (HandlerId) REFERENCES dbo.USERS(UserId) ON DELETE NO ACTION
);
GO

-- =========================================================================
-- NHÓM 4: KHO BIỂU MẪU & NHẬT KÝ PHÁT HÀNH ĐA KÊNH
-- =========================================================================

-- 16. BẢNG TEMPLATES (Kho biểu mẫu nghiệp vụ & văn bản mẫu .docx/.xlsx)
CREATE TABLE dbo.TEMPLATES (
    TemplateId INT IDENTITY(1,1) PRIMARY KEY,
    Code VARCHAR(50) NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Category VARCHAR(50) NOT NULL DEFAULT 'doan_vien',
    CategoryName NVARCHAR(100) NULL,
    Description NVARCHAR(MAX) NULL,
    FileType VARCHAR(20) DEFAULT 'docx',
    FileSize VARCHAR(50) DEFAULT '4.0 KB',
    FilePath VARCHAR(500) NOT NULL,
    DownloadCount INT DEFAULT 0,
    IsActive BIT DEFAULT 1,
    CreatedAt DATETIME2 DEFAULT SYSDATETIME()
);
GO

-- 17. BẢNG PUBLISH_LOGS (Nhật ký phát hành đa kênh sang Website, Fanpage, Zalo OA)
CREATE TABLE dbo.PUBLISH_LOGS (
    LogId INT IDENTITY(1,1) PRIMARY KEY,
    ScheduleId INT NULL,
    ArticleId INT NOT NULL,
    Channel VARCHAR(50) NOT NULL,
    Action VARCHAR(50) NOT NULL,
    Result NVARCHAR(MAX) NULL,
    PublishedAt DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_PUBLISH_LOGS_ARTICLES FOREIGN KEY (ArticleId) REFERENCES dbo.ARTICLES(ArticleId) ON DELETE CASCADE
);
GO