-- =========================================================================
-- CƠ SỞ DỮ LIỆU 5 BẢNG CỐT LÕI - MICROSOFT SQL SERVER (SSMS)
-- Database Name: TDMU_CongDoan_DB
-- =========================================================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = N'TDMU_CongDoan_DB')
BEGIN
    CREATE DATABASE [TDMU_CongDoan_DB];
END
GO

USE [TDMU_CongDoan_DB];
GO

-- Xóa bảng cũ theo thứ tự khóa ngoại
IF OBJECT_ID(N'dbo.VAN_BAN', N'U') IS NOT NULL DROP TABLE dbo.VAN_BAN;
IF OBJECT_ID(N'dbo.TIN_TUC', N'U') IS NOT NULL DROP TABLE dbo.TIN_TUC;
IF OBJECT_ID(N'dbo.NHAN_SU', N'U') IS NOT NULL DROP TABLE dbo.NHAN_SU;
IF OBJECT_ID(N'dbo.TO_CONG_DOAN', N'U') IS NOT NULL DROP TABLE dbo.TO_CONG_DOAN;
IF OBJECT_ID(N'dbo.TO_CHUC', N'U') IS NOT NULL DROP TABLE dbo.TO_CHUC;
GO

-- 1. BẢNG TO_CHUC
CREATE TABLE dbo.TO_CHUC (
    MaToChuc INT IDENTITY(1,1) PRIMARY KEY,
    TenToChuc NVARCHAR(150) NOT NULL,
    NhiemKy NVARCHAR(50) NOT NULL,
    MoTaChucNang NVARCHAR(MAX) NULL,
    ThuTuHienThi INT NOT NULL CONSTRAINT DF_TO_CHUC_ThuTu DEFAULT 1,
    TrangThai BIT NOT NULL CONSTRAINT DF_TO_CHUC_TrangThai DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_TO_CHUC_NgayTao DEFAULT SYSDATETIME()
);
GO

-- 2. BẢNG TO_CONG_DOAN
CREATE TABLE dbo.TO_CONG_DOAN (
    MaToCongDoan INT IDENTITY(1,1) PRIMARY KEY,
    MaDinhDanh NVARCHAR(50) NOT NULL CONSTRAINT UQ_TO_CONG_DOAN_MaDinhDanh UNIQUE,
    TenToCongDoan NVARCHAR(150) NOT NULL,
    ToTruong NVARCHAR(100) NULL,
    EmailLienHe NVARCHAR(100) NULL,
    SoDienThoai NVARCHAR(20) NULL,
    DiaChiVanPhong NVARCHAR(150) NULL,
    TrangThai BIT NOT NULL CONSTRAINT DF_TO_CONG_DOAN_TrangThai DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_TO_CONG_DOAN_NgayTao DEFAULT SYSDATETIME()
);
GO

-- 3. BẢNG NHAN_SU
CREATE TABLE dbo.NHAN_SU (
    MaNhanSu INT IDENTITY(1,1) PRIMARY KEY,
    MaToCongDoan INT NOT NULL,
    MaToChuc INT NULL,
    MaCanBo NVARCHAR(50) NOT NULL CONSTRAINT UQ_NHAN_SU_MaCanBo UNIQUE,
    HoVaTen NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL CONSTRAINT DF_NHAN_SU_GioiTinh DEFAULT N'Nam' CONSTRAINT CK_NHAN_SU_GioiTinh CHECK (GioiTinh IN (N'Nam', N'Nữ', N'Khác')),
    NgaySinh DATE NULL,
    Email NVARCHAR(100) NOT NULL CONSTRAINT UQ_NHAN_SU_Email UNIQUE,
    SoDienThoai NVARCHAR(20) NULL,
    MatKhau NVARCHAR(255) NULL,
    HocHamHocVi NVARCHAR(50) NULL,
    ChucVuCongDoan NVARCHAR(100) NOT NULL CONSTRAINT DF_NHAN_SU_ChucVuCD DEFAULT N'Đoàn viên',
    ChucVuChuyenMon NVARCHAR(100) NULL,
    VaiTroHeThong NVARCHAR(50) NOT NULL CONSTRAINT DF_NHAN_SU_VaiTro DEFAULT 'Contributor' CONSTRAINT CK_NHAN_SU_VaiTro CHECK (VaiTroHeThong IN ('Admin', 'Editor', 'Contributor', 'User')),
    TrangThai BIT NOT NULL CONSTRAINT DF_NHAN_SU_TrangThai DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_NHAN_SU_NgayTao DEFAULT SYSDATETIME(),
    CONSTRAINT FK_NHAN_SU_ToCongDoan FOREIGN KEY (MaToCongDoan) REFERENCES dbo.TO_CONG_DOAN(MaToCongDoan),
    CONSTRAINT FK_NHAN_SU_ToChuc FOREIGN KEY (MaToChuc) REFERENCES dbo.TO_CHUC(MaToChuc) ON DELETE SET NULL
);
GO

-- 4. BẢNG TIN_TUC
CREATE TABLE dbo.TIN_TUC (
    MaTinTuc INT IDENTITY(1,1) PRIMARY KEY,
    MaTacGia INT NOT NULL,
    TieuDe NVARCHAR(255) NOT NULL,
    Slug NVARCHAR(255) NOT NULL CONSTRAINT UQ_TIN_TUC_Slug UNIQUE,
    ChuyenMuc NVARCHAR(100) NOT NULL,
    TomTat NVARCHAR(MAX) NULL,
    NoiDung NVARCHAR(MAX) NOT NULL,
    HinhAnhDaiDien NVARCHAR(255) NULL,
    TrangThai NVARCHAR(50) NOT NULL CONSTRAINT DF_TIN_TUC_TrangThai DEFAULT 'Draft' CONSTRAINT CK_TIN_TUC_TrangThai CHECK (TrangThai IN ('Draft', 'Pending', 'Approved', 'Published', 'Archived')),
    LuotXem INT NOT NULL CONSTRAINT DF_TIN_TUC_LuotXem DEFAULT 0,
    NgayXuatBan DATETIME2 NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_TIN_TUC_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NOT NULL CONSTRAINT DF_TIN_TUC_NgayCapNhat DEFAULT SYSDATETIME(),
    CONSTRAINT FK_TIN_TUC_TacGia FOREIGN KEY (MaTacGia) REFERENCES dbo.NHAN_SU(MaNhanSu)
);
GO

-- 5. BẢNG VAN_BAN
CREATE TABLE dbo.VAN_BAN (
    MaVanBan INT IDENTITY(1,1) PRIMARY KEY,
    MaNguoiDang INT NOT NULL,
    SoHieuVanBan NVARCHAR(100) NOT NULL,
    TenVanBan NVARCHAR(255) NOT NULL,
    LoaiVanBan NVARCHAR(100) NOT NULL,
    CoQuanBanHanh NVARCHAR(150) NOT NULL,
    NgayBanHanh DATE NOT NULL,
    NguoiKy NVARCHAR(100) NULL,
    TepDinhKem NVARCHAR(255) NOT NULL,
    GhiChu NVARCHAR(MAX) NULL,
    NgayDang DATETIME2 NOT NULL CONSTRAINT DF_VAN_BAN_NgayDang DEFAULT SYSDATETIME(),
    CONSTRAINT FK_VAN_BAN_NguoiDang FOREIGN KEY (MaNguoiDang) REFERENCES dbo.NHAN_SU(MaNhanSu)
);
GO
